// console.log("arunkumar")
// console.log("      1 ")
// console.log("     212  ")
// console.log("    32123")
// console.log("   4321234")
// console.log("  543212345")
// console.log("   4321234")
// console.log("    32123")
// console.log("     212")
// console.log("      1")
// console.log("  * *  * * * *    * *     * *   *  *   * *      *   * *   * * *             ")
// console.log(" *   * *   * *    * * *   * *  *   *   * * *   * * *    * *   *      ")
// console.log(" * * * * * * *    * *  *  * * *    *   * *   *   * * *  * * * *      ")
// console.log(" *   * *  *  *    * *   * * *  *   *   * *       * *    * *  *     ")
// console.log(" *   * *   *   * *  *     * *    *  * *  *       * *    * *    *     ")
// console.log("----------------------------------------------------------------")
// console.log("      Name      |   Age |         E-mail           |   Phone.No  ")
// console.log("----------------------------------------------------------------")
// console.log(" S.ARUNKUMAR        21     arunsm1011@gmail.com       8345972411     ")
// console.log(" B.sakthivel        22     sakthivel564@gmail.com     9845632547 ")
console.log('    *         # # #        ')
console.log(" *     *          #          ")
console.log("    *             #      ")
console.log(" *     *           # # #       ")
console.log("    *                  # ")
console.log("            # #    # # #        ")
console.log("              #    #            ")
console.log("              #    #            ")
console.log("              #  # #            ")
// age =49
// email= "java#gmai.com"
// console.log("welcome chief "+name)